// File: Domain/Customer.cs
// Suggested folder: Domain
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAPI_ModNunit.Models
{
    public class Customer
    {
        /// <summary>
        /// Unique identifier for the customer. Auto-generated by the database. 
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }

        /// <summary>
        /// Customer's name (typically a company name).
        /// </summary>
        public string? Name { get; set; }

        /// <summary>
        /// Customer's email address.
        /// </summary>
        public string? Email { get; set; }

        /// <summary>
        /// Collection of phone numbers associated with this customer.
        /// </summary>
        public List<TelephoneNumber>? PhoneNumbers { get; set; } = new List<TelephoneNumber>();
    }
}
