using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAPI_ModNunit.Models
{
    public class Order
    {
        /// <summary>
        /// Unique identifier for the order. Auto-generated by the database.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }

        /// <summary>
        /// Foreign key reference to the Customer who placed this order.
        /// Optional - either CustomerId or CustomerEmail must be provided.
        /// </summary>
        public long? CustomerId { get; set; }

        /// <summary>
        /// Foreign key reference to the Supplier (source) of this order.
        /// </summary>
        [Required(ErrorMessage = "SupplierId is required.")]
        [Range(1, long.MaxValue, ErrorMessage = "SupplierId must be greater than zero.")]
        public long SupplierId { get; set; }

        /// <summary>
        /// The date the order was placed.
        /// </summary>
        [Required(ErrorMessage = "OrderDate is required.")]
        public DateTime OrderDate { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Customer email at the time of order.
        /// Optional - either CustomerId or CustomerEmail must be provided.
        /// </summary>
        [StringLength(200, ErrorMessage = "CustomerEmail cannot exceed 200 characters.")]
        [EmailAddress(ErrorMessage = "Invalid email address format.")]
        public string? CustomerEmail { get; set; }

        /// <summary>
        /// Billing address for the order (required).
        /// </summary>
        [Required(ErrorMessage = "BillingAddress is required.")]
        public Address BillingAddress { get; set; } = null!;

        /// <summary>
        /// Delivery address for the order (optional).
        /// </summary>
        public Address? DeliveryAddress { get; set; }

        /// <summary>
        /// Navigation property to the Supplier.
        /// </summary>
        public Supplier? Supplier { get; set; }

        /// <summary>
        /// Collection of items in this order.
        /// </summary>
        public List<OrderItem>? OrderItems { get; set; } = new List<OrderItem>();

        /// <summary>
        /// Current status of the order in the fulfillment process.
        /// </summary>
        [Required(ErrorMessage = "OrderStatus is required.")]
        public OrderStatus OrderStatus { get; set; } = OrderStatus.Received;

        /// <summary>
        /// Calculated property that returns the total amount of the order.
        /// </summary>
        public decimal TotalAmount => OrderItems?.Sum(oi => oi.Price * oi.Quantity) ?? 0;
    }
}
