using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAPI_ModNunit.Models
{
    public class OrderItem
    {
        /// <summary>
        /// Unique identifier for the order item. Auto-generated by the database.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }

        /// <summary>
        /// Foreign key reference to the Order.
        /// </summary>
        [Required(ErrorMessage = "OrderId is required.")]
        [Range(1, long.MaxValue, ErrorMessage = "OrderId must be greater than zero.")]
        public long OrderId { get; set; }

        /// <summary>
        /// Foreign key reference to the Product.
        /// </summary>
        [Required(ErrorMessage = "ProductId is required.")]
        [Range(1, long.MaxValue, ErrorMessage = "ProductId must be greater than zero.")]
        public long ProductId { get; set; }

        /// <summary>
        /// The quantity of the product ordered.
        /// </summary>
        [Required(ErrorMessage = "Quantity is required.")]
        [Range(1, int.MaxValue, ErrorMessage = "Quantity must be at least 1.")]
        public int Quantity { get; set; }

        /// <summary>
        /// The price per unit of the product at the time of order.
        /// </summary>
        [Required(ErrorMessage = "Price is required.")]
        [Column(TypeName = "decimal(18,2)")]
        [Range(0, double.MaxValue, ErrorMessage = "Price must be greater than or equal to 0.")]
        public decimal Price { get; set; }

        /// <summary>
        /// Navigation property to the Product.
        /// </summary>
        public Product? Product { get; set; }
    }
}
