using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAPI_ModNunit.Models
{
    public class Product
    {
        /// <summary>
        /// Unique identifier for the product. Auto-generated by the database.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }

        /// <summary>
        /// Globally unique product code identifier.
        /// </summary>
        [Required(ErrorMessage = "ProductCode is required.")]
        public Guid ProductCode { get; set; } = Guid.NewGuid();

        /// <summary>
        /// Product name.
        /// </summary>
        [Required(ErrorMessage = "Name is required.")]
        [StringLength(200, ErrorMessage = "Name cannot exceed 200 characters.")]
        public string Name { get; set; } = string.Empty;
    }
}
