using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAPI_ModNunit.Models
{
    public class Supplier
    {
        /// <summary>
        /// Unique identifier for the supplier. Auto-generated by the database.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }

        /// <summary>
        /// Supplier name.
        /// </summary>
        [Required(ErrorMessage = "Name is required.")]
        [StringLength(200, ErrorMessage = "Name cannot exceed 200 characters.")]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Collection of orders from this supplier.
        /// </summary>
        public List<Order>? Orders { get; set; } = new List<Order>();
    }
}
