using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAPI_ModNunit.Models
{
    public class TelephoneNumber
    {
        /// <summary>
        /// Unique identifier for the phone number. Auto-generated by the database and globally unique.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }

        /// <summary>
        /// Foreign key reference to the Customer who owns this phone number.
        /// </summary>
        [Range(1, long.MaxValue, ErrorMessage = "CustomerId must be greater than zero.")]
        public long CustomerId { get; set; }

        /// <summary>
        /// The type of phone number. Must be one of: Mobile, Work, or DirectDial.
        /// </summary>
        [RegularExpression("^(Mobile|Work|DirectDial)$", ErrorMessage = "Type must be Mobile, Work, or DirectDial.")]
        public string? Type { get; set; }

        /// <summary>
        /// The phone number string in any format.
        /// </summary>
        public string? Number { get; set; }

        /// <summary>
        /// Initializes a new instance of the TelephoneNumber class.
        /// </summary>
        public TelephoneNumber() { }
    }

}
